version: "2"
services:
  app:
    build: .
#    links:
#      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - myvolume1:/FarmerRegistryService/
    networks:
      - mynet
    restart: "always"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_USER: root
#      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - myvolume2:/var/lib/mysql
    networks:
      - mynet

volumes:
  myvolume1:
  myvolume2:

networks:
  mynet:
    driver: bridge

