#version: "2"
#services:
#  app:
#    build: .
#    links:
#      - db
#    ports:
#      - "5000:5000"
#  db:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE : farmer_registry1
#      MYSQL_ROOT_PASSWORD : root
#
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/:ro

version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - app-db

  app-db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    environment:
    - MYSQL_ROOT_PASSWORD=""
    - MYSQL_DATABASE=farmer_registry1
    ports:
      - 3306:3306
