DROP TABLE IF EXISTS FARMER_DETAILS;
CREATE TABLE FARMER_DETAILS(
    FARMER_ID INTEGER PRIMARY KEY,
    FARMER_NAME TEXT NOT NULL,
    MOBILE_NUMBER INTEGER,
    VILLAGE_NAME TEXT NOT NULL,
    ADDRESS TEXT
)