# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: farmer-registry-service-svc
spec:
  type: LoadBalancer
  selector:
    app: farmer_registry_service
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000